######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 3 11:07:40 2010
######################################################################

TARGET = helloworld
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += release console

# Input
HEADERS += helloworld.h goodbyeworld.h
SOURCES += helloworld.cpp main.cpp goodbyeworld.cpp
